ga:
  epoch: 1000
  pop_size: 1000
  pr: 0.3
  pc: 0.9
  pm: 0.05
termination:
  max_epoch: 1100
  max_fe: 80000
  max_time: 10.5
  max_early_stop: 25
crossover: "one_point"
mutation: "bit_flip"
objective: "sharpe"
selection: "tournament"
init: "uniform"
seed: 42
