ga:
  num_generations: 250
  num_parents_mating: 10
  initial_population: 1000
  crossover_probability: 0.3
  mutation_probability: 0.05
  termination:
    minimal_generations: 50
    epsilon: 1e-4
data:
  start_date: '2024-03-30'
  end_date: '2024-04-30'
  stocks:
    - AAPL
    - MSFT
    - GOOG
crossover: "arithmetic"
mutation: "gaussian"
objective: "sharpe"
selection: "tournament"
init: "dirichlet"
seed: 42
