ga:
  num_generations: 1000
  num_parents_mating: 10
  initial_population: 1000
  crossover_probability: 0.3
  mutation_probability: 0.05
  num_genes: 10
termination:
  max_epoch: 1100
  max_fe: 80000
  max_time: 10.5
  max_early_stop: 25
crossover: "arithmetic"
mutation: "mutate_gaussian"
objective: "sharpe"
selection: "tournament"
init: "uniform"
seed: 42
